apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: firstpod
spec:
  initContainers:
  - name: init-container
    image: adikul30/init-container
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
  containers:
  # - name: serviceA
  #   image: kennethreitz/httpbin
  #   ports:
  #   - containerPort: 80
  - name: client
    image: adikul30/client-service
    env:
      - name: SVC_NAME
        value: "client"
      - name: server-ip
        value: "10.244.0.7"
    ports:
    - containerPort: 80
  - name: proxy
    image: adikul30/sidecar-proxy
    env:
      - name: SVC_NAME
        value: "client"
    ports:
    - containerPort: 8000

