apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  labels:
    app: secondpod
spec:
  initContainers:
  - name: init-container
    image: adikul30/init-container
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
  containers:
  # - name: serviceA
  #   image: kennethreitz/httpbin
  #   ports:
  #   - containerPort: 80
  - name: service-b
    image: adikul30/server-service
    env:
      - name: SVC_NAME
        value: "svc-B"
    ports:
    - containerPort: 80
  - name: proxy
    image: adikul30/sidecar-proxy
    env:
      - name: SVC_NAME
        value: "svc-B"
    ports:
    - containerPort: 8000

